# Generated by Django 6.0.4 on 2026-04-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subreddit", models.CharField(max_length=100)),
                ("keyword", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["subreddit", "keyword"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "subreddit", "keyword"),
                        name="unique_monitor_per_user_subreddit_keyword",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reddit_item_id", models.CharField(max_length=255)),
                ("title", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("permalink", models.URLField()),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("monitor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tracking.monitor")),
            ],
            options={
                "ordering": ["-occurred_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("monitor", "reddit_item_id"),
                        name="unique_match_per_monitor_reddit_item",
                    ),
                ],
            },
        ),
    ]
