# Generated by Django 5.2.14 on 2026-05-23 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_add_notification_cadence_to_monitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ['subreddit', 'match_mode', 'keyword', 'semantic_fingerprint']},
        ),
        migrations.RemoveConstraint(
            model_name='monitor',
            name='unique_monitor_per_user_subreddit_keyword',
        ),
        migrations.AddField(
            model_name='match',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_mode',
            field=models.CharField(choices=[('keyword', 'Keyword'), ('semantic', 'Semantic'), ('keyword_semantic', 'Keyword + semantic')], default='keyword', max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='match_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='match_mode',
            field=models.CharField(choices=[('keyword', 'Keyword'), ('semantic', 'Semantic'), ('keyword_semantic', 'Keyword + semantic')], default='keyword', max_length=32),
        ),
        migrations.AddField(
            model_name='monitor',
            name='semantic_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='semantic_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.UniqueConstraint(fields=('user', 'subreddit', 'match_mode', 'keyword', 'semantic_fingerprint'), name='unique_monitor_per_user_subreddit_mode'),
        ),
    ]
