# Generated by Django 5.2.14 on 2026-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_matchdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted')], default='new', max_length=16),
        ),
    ]
