#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Interface: CELERY_WORKER_CONCURRENCY controls worker memory use on small VPS deployments.
exec celery -A config.celery_app worker -l INFO --concurrency="${CELERY_WORKER_CONCURRENCY:-1}"
