# Generated by Django 5.2.14 on 2026-06-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keyword_extraction_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Keyword extraction URL'),
        ),
    ]
