# Generated by Django 6.0.4 on 2026-04-26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubredditFetchState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subreddit", models.CharField(max_length=100, unique=True)),
                ("last_seen_fullname", models.CharField(blank=True, max_length=255)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["subreddit"],
            },
        ),
        migrations.CreateModel(
            name="RedditItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reddit_id", models.CharField(max_length=255, unique=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("post", "Post"), ("comment", "Comment")],
                        max_length=20,
                    ),
                ),
                ("subreddit", models.CharField(max_length=100)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("title", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("permalink", models.URLField()),
                ("occurred_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["subreddit", "-occurred_at"],
                        name="reddit_redd_subredd_00af07_idx",
                    ),
                ],
            },
        ),
    ]
