# Generated by Django 5.2.14 on 2026-06-25 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_add_fetch_state_lane'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(db_index=True, max_length=100)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto (on monitor add)'), ('scheduled', 'Scheduled')], default='scheduled', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('rate_limited', 'Rate limited')], default='running', max_length=16)),
                ('matches_created', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['subreddit', '-started_at'], name='reddit_fetchrun_sub_idx')],
            },
        ),
    ]
