#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Interface: WEB_CONCURRENCY controls Django memory use on small VPS deployments.
exec gunicorn config.asgi \
  --bind 0.0.0.0:5000 \
  --chdir=/app \
  --workers "${WEB_CONCURRENCY:-1}" \
  -k uvicorn_worker.UvicornWorker
