name: CI

on:
  pull_request:
    branches: ['main']
    paths-ignore: ['docs/**']

  push:
    branches: ['main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      # Consider using pre-commit.ci for open source project
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  pytest:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://chattersift:chattersift@localhost:5432/chattersift
      REDIS_URL: redis://localhost:6379/0

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install system services
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql redis-server
          sudo systemctl start postgresql
          sudo systemctl start redis-server

      - name: Create test database
        run: |
          sudo -u postgres psql --command="CREATE USER chattersift WITH CREATEDB PASSWORD 'chattersift';"
          sudo -u postgres createdb --owner=chattersift chattersift

      - name: Install Python dependencies
        run: uv sync --locked --all-groups

      - name: Check DB Migrations
        run: uv run python manage.py makemigrations --check

      - name: Run DB Migrations
        run: uv run python manage.py migrate

      - name: Run Django Tests
        run: uv run pytest
